name: CI/CD Pipeline Backend Batttrack

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint and test
      run: |
        pip install pytest
        pytest

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t bestbest/api_batttrack .

    - name: Push to Docker Hub
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: bestbest/api_batttrack:latest

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to host
      run: |
        ssh -o StrictHostKeyChecking=no root@119.59.102.68 '
          docker pull bestbest/api_batttrack:latest &&
          cd /home/batter-track &&
          docker compose down &&
          docker compose up
        '
